### ISSUE TITLE
实体类习惯用 _ 下划线，代码生成器能自动判断实体类名称么？

### ISSUE THREAD

**Issue by Wizzercn** [enilu/nutzwk-code-generator#10]
1、POJO类叫啥类名，代码就使用什么类名如何，别做处理； 
2、ID:${args[0]}  控制器删除，这个是有可能为空的，可以改成：
    @At({"/delete/?", "/delete"})
    @Ok("json")
    @RequiresPermissions("cms.content.article.delete")
    @SLog(tag = "删除文章", msg = "ID:${args[2].getAttribute('id')}")
    public Object delete(String oneId, @Param("ids") String[] ids, HttpServletRequest req) {
        try {
            if (ids != null && ids.length > 0) {
                cmsArticleService.delete(ids);
                req.setAttribute("id", org.apache.shiro.util.StringUtils.toString(ids));
            } else {
                cmsArticleService.delete(oneId);
                req.setAttribute("id", oneId);
            }
            return Result.success("system.success");
        } catch (Exception e) {
            return Result.error("system.error");
        }
    }

**Comment by Wizzercn** [comment]
类名别做处理，否则生成的代码找不到类。。

**Comment by enilu** [comment]
类名下划线好不习惯啊，我改改了

**Comment by Wizzercn** [comment]
@enilu 其实和下划线没关系，类名叫啥就是啥就可以了。。
