### ISSUE TITLE
关于路径

### ISSUE THREAD

**Issue by Wizzercn** [enilu/nutzwk-code-generator#14]
/private/we/we_order_goodss  
这个生成的路径格式，能否变成：
/private/we/order/goods   

1、带 _ 号的，每个作为文件夹名称；
2、不要在后面加s；

习惯问题，每次生成后还要一个个改，不能达到完全自动化，用起来好不爽。- -

**Comment by enilu** [comment]
@Wizzercn s可以去掉，we_order_goods 生成/we/order/good 感觉有点怪呢

**Comment by Wizzercn** [comment]
goodss  是2个s  只用去掉一个，我的POJO类是 We_order_goods ，后面的s是巧合而已……@enilu

**Comment by enilu** [comment]
嗯嗯，明白，之前uri和页面文件夹名称都是取表名称的复数形式，去掉就完了 @Wizzercn

**Comment by Wizzercn** [comment]
![qq 20160901145911](https://cloud.githubusercontent.com/assets/2408114/18158255/b79e3248-7054-11e6-8879-ae2a4fb80777.png)

路径不对..

**Comment by Wizzercn** [comment]
@enilu
