### ISSUE TITLE
配置了code.json 运行出错

### ISSUE THREAD

**Issue by TomYule** [enilu/nutzwk-code-generator#15]
配置如下
`{
  dataSource : {
    type : "com.alibaba.druid.pool.DruidDataSource",
    events : {
      depose : 'close'
    },
    fields : {
      driverClassName : "com.mysql.jdbc.Driver",
      url : "jdbc:mysql://192.168.1.127:3306/bluejay",
      username : "root",
      password : "root",
      maxWait: 20000,
      defaultAutoCommit : false
    }
  },
  loader:{
    //根据实体生成代码
    type:'nuoshang.bluejay.bean.Return_goods'
    //根据表结构生成代码
    //        type:'cn.enilu.common.code.TableDescLoader'
  }
}`

对应的类
`package nuoshang.bluejay.bean;
import java.io.Serializable;
import org.nutz.dao.entity.annotation._;
/_*
- 通过 DBCodeCreateTool 代码自动生成
- @author yuhaiming
- @time 2016-08-09 09:35:16
  _/
  @Table("return_goods")
  public class Return_goods implements Serializable{
  private static final long serialVersionUID = 1L;
  /_********\* attribute **********_/
  /**__退货编号 *_**/
  @Id
  @Column("return_id")
  private int return_id;
  
  /***_商品编号 ***_/
  @Column("re_goods_id")
  private int re_goods_id;
  /***_副订单编号 ***_/
  @Column("ret_order_item_id")
  private int ret_order_item_id;
  /***_用户编号 ***_/
  @Column("ret_user_id")
  private int ret_user_id;
  /***_物流信息 ***_/
  @Column("ret_logi_id")
  private String ret_logi_id;
  /***_退货理由 ***_/
  @Column("reason")
  private String reason;
  /***_备注内容 ***_/
  @Column("detail")
  private String detail;
  /***_退货状态 ***_/
  @Column("status")
  private int status;
  /***_退货时间 ***_/
  @Column("return_time")
  private java.sql.Timestamp return_time;
  /***_收货时间 ***_/
  @Column("delivery_time")
  private java.sql.Timestamp delivery_time;
  public Return_goods() {}
  public Return_goods(int return_id, int re_goods_id, int ret_order_item_id, int ret_user_id, String ret_logi_id, String reason, String detail, int status, java.sql.Timestamp return_time, java.sql.Timestamp delivery_time) {
      this.return_id = return_id;
      this.re_goods_id = re_goods_id;
      this.ret_order_item_id = ret_order_item_id;
      this.ret_user_id = ret_user_id;
      this.ret_logi_id = ret_logi_id;
      this.reason = reason;
      this.detail = detail;
      this.status = status;
      this.return_time = return_time;
      this.delivery_time = delivery_time;
  }
  /*********\* get/set ***********/
  public int getReturn_id() {
      return return_id;
  }
  public void setReturn_id(int return_id) {
      this.return_id = return_id;
  }
  public int getRe_goods_id() {
      return re_goods_id;
  }
  public void setRe_goods_id(int re_goods_id) {
      this.re_goods_id = re_goods_id;
  }
  public int getRet_order_item_id() {
      return ret_order_item_id;
  }
  public void setRet_order_item_id(int ret_order_item_id) {
      this.ret_order_item_id = ret_order_item_id;
  }
  public int getRet_user_id() {
      return ret_user_id;
  }
  public void setRet_user_id(int ret_user_id) {
      this.ret_user_id = ret_user_id;
  }
  public String getRet_logi_id() {
      return ret_logi_id;
  }
  public void setRet_logi_id(String ret_logi_id) {
      this.ret_logi_id = ret_logi_id;
  }
  public String getReason() {
      return reason;
  }
  public void setReason(String reason) {
      this.reason = reason;
  }
  public String getDetail() {
      return detail;
  }
  public void setDetail(String detail) {
      this.detail = detail;
  }
  public int getStatus() {
      return status;
  }
  public void setStatus(int status) {
      this.status = status;
  }
  public java.sql.Timestamp getReturn_time() {
      return return_time;
  }
  public void setReturn_time(java.sql.Timestamp return_time) {
      this.return_time = return_time;
  }
  public java.sql.Timestamp getDelivery_time() {
      return delivery_time;
  }
  public void setDelivery_time(java.sql.Timestamp delivery_time) {
      this.delivery_time = delivery_time;
  }
  }
  `

**Comment by enilu** [comment]
@TonyYule 
type:'nuoshang.bluejay.bean.Return_goods' //根据表结构生成代码 // 
这行不要动，恢复回去
