### ISSUE TITLE
代码生成index页面少了一串代码导致detail页面数据只能显示第一次打开的数据

### ISSUE THREAD

**Issue by sunhai1988** [enilu/nutzwk-code-generator#18]
$("#dialogDetail").on("hidden.bs.modal", function() {
            $(this).removeData("bs.modal");
 });

index.vm 加上以上代码

 $(function () {
        initDatatable();

>    $("#dialogDetail").on("hidden.bs.modal", function() {
>             $(this).removeData("bs.modal");
>         });

```
});
```

**Comment by Wizzercn** [comment]
https://github.com/enilu/nutzwk-code-generator/issues/18

重复提交 @enilu MAVEN仓库更新下？

**Comment by enilu** [comment]
已提交更新到maven仓库
