### ISSUE TITLE
dialogDeleteCheck和dialogDelete 可以合并成一个模态框

### ISSUE THREAD

**Issue by Wizzercn** [enilu/nutzwk-code-generator#6]
dialogDeleteCheck 删除，JS里批量调用改成 --> dialogDelete

请先选择要删除的${table.Label}！   表名不合适吧？
-->
请先选择要删除的项！

**Comment by enilu** [comment]
${table.Label} 默认取的是java实体的注释，例如下面代码取得是“国家”，如果没有注释的时候再取表名称：

`

@Comment("国家")
@Table("dic_country")
public class DicCountry  extends Model implements Serializable {
    private static final long serialVersionUID = 1L;
    @Name
    @Prev(els = {@EL("uuid()")})
    private String id;
        ....
}

```
`
```

**Comment by enilu** [comment]
不过没有表名的时候确实用“项“比较合适，我改下
